# https://gitlab.com/pages/hugo/-/blob/master/.gitlab-ci.yml

# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

hugo:
  script:
  - hugo
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

# https://docs.web3.storage/how-tos/work-with-car-files#go-ipfs
build_car:
  image:
    name: ipfs/go-ipfs
    entrypoint: [""]
  script:
  - ipfs init
  - CID=$(ipfs add -Q -r public)
  - echo "${CID}"
  - mkdir car
  - ipfs dag export "${CID}" > "car/output.car"
  artifacts:
    paths:
    - public
    - car
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  needs: ["hugo"]

# https://docs.web3.storage/reference/http-api/#operation/post-car
store_car_web3storage:
  image:
    name: curlimages/curl
  script:

  # Split large car files?
  # https://github.com/nftstorage/carbites-cli/
  # - carbites split big.car --size 100MB --strategy simple

  - curl -F file=@car/output.car -H "Authorization: Bearer ${WEB3STORAGE_TOKEN}" -X POST https://api.web3.storage/car
  artifacts:
    paths:
    - car
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  needs: ["build_car"]
  
# IPFS stuff here:
# https://github.com/ipfs-shipyard/ipfs-dns-deploy
# or maybe this:
# http://docs.ipfs.io.ipns.localhost:8080/how-to/work-with-pinning-services/

# Broken - seems like maybe running ipfs inside a gitlab-runner doesn't work - no network access?
#pin_to_ipfs:
#  image:
#    name: ipfs/go-ipfs
#    entrypoint: [""]
#  script:
#  - ipfs init
#  - CID=$(ipfs add -Q -r public)
#  - echo "${CID}"
#  - ipfs pin remote service add pinata https://api.pinata.cloud/psa "${PINATA_JWT}"
#  - ipfs pin remote add --service=pinata "${CID}"
#  artifacts:
#    paths:
#    - public
#  rules:
#    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
#  needs: ["hugo"]

# Broken example with Pinana
# Maybe try this instead: https://docs.pinata.cloud/api-pinning/pin-file#pinning-a-directory-example
# curl -F file=@public/ -H "Authorization: Bearer ${PINATA_JWT}" -X POST https://api.pinata.cloud/pinning/pinFileToIPFS
