baseURL: 'https://evanstucker.com/'
languageCode: 'en-us'
title: 'Evans Tucker'
#theme: 'beautifulhugo'
#theme: 'ink-free'
#theme: 'ananke'
theme: 'PaperMod'
copyright: '[CC0](http://creativecommons.org/publicdomain/zero/1.0/) Evans Tucker has waived all copyright and related or neighboring rights.'
#copyright: '<p xmlns:dct="http://purl.org/dc/terms/" xmlns:vcard="http://www.w3.org/2001/vcard-rdf/3.0#"><a rel="license"href="http://creativecommons.org/publicdomain/zero/1.0/"><img src="http://i.creativecommons.org/p/zero/1.0/88x31.png" style="border-style: none;" alt="CC0" /></a><br />To the extent possible under law,<a rel="dct:publisher"href="https://evanstucker.com/"><span property="dct:title">Evans Tucker</span></a>has waived all copyright and related or neighboring rights to<span property="dct:title">Evans Tucker</span>.This work is published from:<span property="vcard:Country" datatype="dct:ISO3166"content="US" about="https://evanstucker.com/">United States</span>.</p>'
timeZone: 'Etc/UTC'
menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
