#baseURL: 'https://ipfs.evanstucker.com/'
baseURL: ''

# Need to use `relativeURLs: true` to fix this error:
# The resource from blahblah.css was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).
relativeURLs: true

# Not sure if this is desirable or not, but leaving it here so I remember to read more about it later.
#uglyurls: true

languageCode: en-us
title: Evans Tucker

# OK themes, but not my favorite.
#theme: beautifulhugo

# These themes don't display images inline - you have to click into the post. Lame.
theme: PaperMod
#theme: ananke
#theme: anubis
#theme: binario
#theme: eureka
#theme: terminal

# Broken themes
#theme: Blonde
#theme: even
#theme: gokarna
#theme: hugo-coder
#theme: hugo-theme-monochrome
#theme: ink-free

copyright: '[CC0](http://creativecommons.org/publicdomain/zero/1.0/) Evans Tucker has waived all copyright and related or neighboring rights.'
#copyright: '<p xmlns:dct="http://purl.org/dc/terms/" xmlns:vcard="http://www.w3.org/2001/vcard-rdf/3.0#"><a rel="license"href="http://creativecommons.org/publicdomain/zero/1.0/"><img src="http://i.creativecommons.org/p/zero/1.0/88x31.png" style="border-style: none;" alt="CC0" /></a><br />To the extent possible under law,<a rel="dct:publisher"href="https://evanstucker.com/"><span property="dct:title">Evans Tucker</span></a>has waived all copyright and related or neighboring rights to<span property="dct:title">Evans Tucker</span>.This work is published from:<span property="vcard:Country" datatype="dct:ISO3166"content="US" about="https://evanstucker.com/">United States</span>.</p>'
timeZone: 'UTC'
menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
params:
  env: production
  ShowShareButtons: true
socialIcons:
  - name: "twitter"
    url: "https://twitter.com"
  - name: "linkedin"
    url: "https://linkedin.com"
  - name: "reddit"
    url: "https://reddit.com"
  - name: "facebook"
    url: "https://facebook.com"
